- tiny_bvh.h
There's a suppression in place for MSVC. Extend it to GCC which also complains, while excluding clang which doesn't.
In the future it may make sense to pre-define 'compiler tests' up front, so there's only one definition of them.
> Extend '-Wmaybe-uninitialized' suppression to GCC.

- tiny_bvh.h
- tiny_bvh_renderer.cpp
Fixes the following two warnings from clang, and GCC which also dislikes the bare variable in `printf` (-Wformat-security)
Hopefully it doesn't break MSC.
```console
clang++-18 -O2 -Wall -std=c++20 -ggdb -march=native -mavx tiny_bvh_renderer.cpp -o tiny_bvh_renderer
In file included from tiny_bvh_renderer.cpp:4:
./tiny_bvh.h:508:51: warning: suggest braces around initialization of subobject [-Wmissing-braces]
508 |         ALIGNED( 64 ) unsigned int count[3][BVHBINS] = { 0 };   // 96 bytes
|                                                          ^
|                                                          {}
tiny_bvh_renderer.cpp:87:44: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
87 |                 line[120] = '\n', line[121] = 0, printf( …
```
> More fixes for GCC and Clang warnings.

- tiny_bvh.h
Only relevant when TINYBVH_IMPLEMENTATION isn't defined
> Fix header namespace closure

- tiny_bvh_fenster.cpp
The code gen isn't _exactly_ the same before-and-after, but it's very minor. Some timings in the post after this.
The GCC diff is less clean and slightly worse-looking, but the clang one looks okay to me.
I understand if you prefer the casting in the end.
(Before this example was updated, I got it bit-exact by using adding a conversion function[^1] to the `TriVertex` type.
I imagine it would be possible to do the same directly on the `bvhvec4`, but that's a more intrusive change.)
[^1]: i.e `operator bvhvec3&() const { return *(bvhvec3*)(this); }`
```diff
$ diff -u asm-orig-clang++-19-tiny_bvh_fenster.s asm-new-clang++-19-tiny_bvh_fenster.s 
--- asm-orig-clang++-19-tiny_bvh_fenster.s	2024-11-02 22:15:59.183094736 +0100
+++ asm-new-clang++-19-tiny_bvh_fenster.s	2024-11-02 …
```
> Remove explicit casts.

- tiny_bvh_speedtest.cpp
Overflow turns index negative. Enforce unsigned result.
> Fix crash in tiny_bvh_speedtest.

- .github/workflows/tinybvh_sdk_ci.yml
- CMakeLists.txt
- tiny_bvh_fenster.cpp
My attempt of enabling CMake to build all executables.
I am far from a CMake expert. I tried to make it as explicit and simple as possible to read/follow.
Only `tiny_bvh_test` is actually run, but this should greatly increase the chance of catching build-breaking changes on CI.
> cmake: build all executables

- tiny_bvh_test.cpp
This greatly increases the chance of catching breakage.
> Test the AVX builder too.

- CMakeLists.txt
- tiny_bvh.h
- tiny_bvh_speedtest.cpp
Hello! I'm playing with WASM through EMSCRIPTEN and decided to test the library to it 😄
Most of the changes are to the CMake file to get the right flags to the compiler.  
There are two big limitations though:
- Fenster is not supported as that would require a WebGL/WebGPU context to render
- OpenMP is not working. More info in the CMake file, but the short story is that the OpenMP library was recently ported and the lib is not included by default with the compiler (I might try later to compile it and link it, but probably won't commit it as that'll be a big change)
From running in my Chrome browser, I get the next numbers (MT numbers are wrong as OpenMP is not enabled):
```
tiny_bvh version 0.7.2 performance statistics (emcc 3.1 build) …
```
> Support for WASM with EMSCRIPTEN

- tiny_bvh.h
- tiny_bvh_fenster.cpp
- tiny_bvh_speedtest.cpp
Just a naive NEOM implementation, kept the same structure of BuildAVX & Intersect_AltSoA for better reference
Tested on M2 MacBook, result below:
> Add naive ARM Neon port for BuildNEON() & Intersect_AltSoA()

- tiny_bvh_speedtest.cpp
Bit of mess define-wise. Anyway.
```console
tiny_bvh version 0.8.0 performance statistics (gcc 14.2 build)
running on AMD Ryzen 7 5800X3D 8-Core Processor           
...
tiny_bvh version 0.8.0 performance statistics (clang 19.1 build)
running on AMD Ryzen 7 5800X3D 8-Core Processor           
```
> CPU detection for GCC/clang.

- tiny_bvh.h
- tiny_bvh_fenster.cpp
- tiny_bvh_speedtest.cpp
- tiny_ocl.h
Adds a struct BVHContext that contains function pointers to possibly user-defined allocation functions.
Removes macros and add default malloc/free functions per platform.
For now, done only for the tinybvh library but I think it should also be done for the tinyocl one(?).
This allows users to manage the memory allocations themselves.
> Adds the possibility to use user-defined allocation functions in tinybvh

- traverse.cl
I was reciving this error on AMD RX 570 GPU
error: token is not a valid binary operator in a preprocessor subexpression
#elif define ISNVIDIA // 2080, 3080, 4080,
> ISNVIDIA preprocessor fix

- tiny_ocl.h
AMD Radeon 6700 XT returns "gfx1031" for CL_DEVICE_NAME.
I also tried CL_DEVICE_VENDOR and it returned "Advanced Micro Devices, Inc.", maybe this could be easier to check.
> add a new AMD gpu name to tiny_ocl.h

- tiny_bvh.h
- tiny_ocl.h
As gcc and clang are now making the size a multiple of the alignment, the 3 targets can be simplified into 1
> Simplified aligned memory functions for Emscripten

- external/fenster.h
- tiny_bvh.h
- tiny_bvh_fenster.cpp
- tiny_bvh_speedtest.cpp
Minor correction to the tiny_bvh.h file (correct steps computations in the Intersect_Afra function)
In speedtest, use same scene loading as fenster to check the scene data in two directories
Minimize changes to the external fenster.h file
Update fenster project to use fenster inputs management (should be multi-platform instead of only win32)
> Changes to the fenster project

- README.md
- external/fenster.h
- tiny_bvh.h
- tiny_bvh_fenster.cpp
- tiny_bvh_speedtest.cpp
- traverse.cl
- vcproj/tiny_bvh_fenster.vcxproj
- vcproj/tiny_bvh_minimal.vcxproj
- vcproj/tiny_bvh_renderer.vcxproj
- vcproj/tiny_bvh_speedtest.vcxproj
Merging dev into main:
* Double-precision ray tracing support
* Preparations for TLAS traversal
* TLAS also means: building over set of AABBs
* Vert ptr now updated on all build calls
* Midpoint split builder (lower-bound on build time)
* Many smaller fixes and adjustments.
> Merging dev into main

- tiny_bvh.h
Pretty useful to have the enum size defined, especially for FFI safety. I guess that's not backward compatible tho.
> Use enum classes

- tiny_bvh.h
- tiny_bvh_speedtest.cpp
Sorry for the drive by cleanup, I have a plugin to remove trailing whitespaces, didn't realize since it autoruns on save :) If you want I can eventually revert those changes.
Would be great to add bound checks to the slice in debug mode. Haven't done that yet. Should we add a `DEBUG` define?
> Add bvhvec4slice to Build()/BuildHQ()

- tiny_bvh.h
The built in vector types for tinybvh work great, but converting between these vectors and other math library vectors is cumbersome.
This PR hides the tinybvh vector types behind an ifndef guard, allowing library users to override the vector types with their own (see comment in PR). 
As long as the supplied vector types size and alignment is the same as tinybvh's, performance should not be impacted.
> Allow custom vector types to be used with tinybvh.

- README.md
- tiny_bvh.h
- vcproj/tiny_bvh_minimal.vcxproj
- vcproj/tiny_bvh_pt.vcxproj
- vcproj/tiny_bvh_renderer.vcxproj
- vcproj/tiny_bvh_speedtest.vcxproj
Second merge today, but this one completes some open issues:
* Slices now available for all builders (old interface also still available!);
* Proper optimization settings for all VS projects;
* Proper working folder (stored in .user...) now set.
Also, we now have 14 contributors. Amazing!
> Merging dev to main

- tiny_bvh.h
- tiny_bvh_fenster.cpp
- tiny_bvh_minimal.cpp
- tiny_bvh_pt.cpp
- tiny_bvh_speedtest.cpp
Major API overhaul based on discussion with David Peicho:
Instead of having one big BVH class, there is now multiple classes, one for each layout. Only the 'BVH' layout (formerly: WALD_32BYTE) and 'BVH_Double' can be built; all others are constructed from other types. In most cases from BVH itself, e.g.: BVH_GPU (formerly known as Aila_Laine) now takes a const BVH reference in it's constructor.
Repeated updates can be done with calls to ConvertFrom; buffers will only be re-allocated in that case if capacity is exceeded. This is the same behavior we had before.
This breaks existing applications. One exception: the 'minimal' example works without changes. :)
See the Fenster app for a good example of building one type and converting to a second layout.
See Speedtest for extensive use of all …
> API overhaul.

- tiny_bvh_speedtest.cpp
This removes the OpenMP parallelism directives and introduces parallelism based on C++11 threads. I have checked the benchmark results, and the timings for the parallel runs were more or less the same.
> Replace OpenMP with cpp11 threads

- tiny_bvh_fenster.cpp
Depth buffer never got released in ``Tick()``
> Fixed memory leak in tiny_bvh_fenster

- wavefront.cl
These are OpenCL functions that might speed up the code a bit. Especially in hemisphere function.
> native_recip and fast_normalize

- tiny_bvh.h
There's one more wasm simd header being pulled in when TINYBVH_NO_SIMD is defined. Added a ifndef guard around that so it will fall back to the non-simd case.
> fix including of wasm simd header with tinybvh_no_simd

- .github/workflows/tinybvh_sdk_ci.yml
- CMakeLists.txt
Presumably the change of github's 'ubuntu-latest' image [to 24.04](https://github.com/actions/runner-images/issues/10636) meant that the X11 dev libraries were no longer available by default. No doubt more will break as the Wayland future creeps up on us, but that's for another day.
Fixes #79
> Install libx11-dev on Ubuntu

- tiny_bvh_fenster.cpp
- tiny_bvh_test.sln
This issue was already fixed in Dec. But looks like it's still an issue.
Looking at the [history](https://github.com/jbikker/tinybvh/commits/main/tiny_bvh_fenster.cpp) of ``tiny_bvh_fenster.cpp``, after my old pr #58  got merged. Commit 05e07c2ceea2166f0dac0e7d868b65c074acffbf seemed to revert the change unknowingly.
Then on Dec 16 @TheSFReader fixed it again with commit 57eb3bc512bad52faa2c80c9b7733abf8c264cf5. But then the fix got moved to ``Shutdown()`` by @jbikker in commit a2b4fe07ae4e93cc4377877fefd7f935ce4fecf7 even though the buffers get allocated every frame. Not sure why this allocation is here in the first place? There is already a ``rays`` and ``depts`` buffer in global space that gets allocated in ``Init()``.
tiny_bvh_fenster is the default start-up project so anyone who …
> Memory leak and start-up project

- README.md
- tiny_bvh.h
- tiny_bvh_anim.cpp
- tiny_bvh_collide.cpp
Tinybvh now properly compiles when not using NEON or AVX but still instantiating BVH_SoA or one of the other SIMD structures.
> Fix issue #95.

- tiny_bvh.h
1. Corrects multiply defined symbol linker errors when including tiny_bvh.h in more than one CPP file.
2. Replace `static inline` with just `inline` for the functions declared that way, since `static` has no semantic meaning with `inline` also declared.
> Mark all functions `inline`

- tiny_bvh.h
This PR fixes issue #105 by not assuming msvc is used when `_MSC_VER` is defined. This is not always the case and should be enforced by checking `!defined(__clang__)`.
> Fix compilation on clang

- tiny_bvh.h
The old code somehow fails to retrieve the correct lane data, leading to stack corruption with incorrect node indices, especially when optimization flags are enabled.
Not quite sure why, but these changes are currently working for me...
> Fix BVH4_CPU traversal

- tiny_bvh.h
This was a leftover from changing the hard defines to variables in BVHBase; now fixed.
> Fixed C_INT and C_TRAV.

- tiny_bvh.h
I tried to use tinybvh with custom vector types today and found a few compiler errors when building, so I made a few corrections to make it more usable (most of it was to remove the call to .cell member, make a function for halfArea calculation, and added a const [] operator for const references). Hope it helps!
> Corrections when using custom vector types

- tiny_bvh.h
I had created an issue for this (https://github.com/jbikker/tinybvh/issues/143), but then decided to do a pull request because it is an easy change. 
Shouldn't the dist2 computation be wrt node->aabbMin and node->aabbMax ?
Otherwise, I think that check is not actually doing anything because pos is always inside (bmin,bmax), so dist2 is always 0 because none of the dist2 if is true, meaning the dist2 <= r2 is actually always true, so no node culling is done at all based on distance.
As a bonus, wouldn't it help more to move this culling before the isLeaf() check, so that it is not only performed in the leaf nodes, to have more aggressive pruning asap.
Don't know if anything I've said is correct or makes sense, but leaving it here in case it helps. In my case, this fix + pruning before …
> Fix BVH::IntersectSphere using sphere node aabb instead of current node aabb

- tiny_bvh_fenster.cpp
some spheres were in the wrong positions due to a wrong use of a variable in one of the recursive calls.
> fix sphere flake creation functions

- tiny_bvh.h
1- Motivation:
In Android NDK version 28.0.13004108 and later, the following error is raised:
```
tinybvh/tiny_bvh.h:229:25: error: use of undeclared identifier
'_aligned_malloc'; did you mean 'aligned_alloc'?
229 |         return size == 0 ? 0 : _aligned_malloc( 64, make_multiple_64( size ) );
|                                ^~~~~~~~~~~~~~~
|                                aligned_alloc
C:/Users/<ldap>/AppData/Local/Android/Sdk/ndk/28.0.13004108/toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/include/stdlib.h:93:29: 
note: 'aligned_alloc' declared here
93 | __nodiscard void* _Nullable aligned_alloc(size_t __alignment, size_t __size) __INTRODUCED_IN(28);
|                             ^
```
2- Suggested solution:
Use 'aligned_alloc' function that has become available in NDK …
> Use 'aligned_alloc' function for Android NDK 28 and later.

- tiny_bvh.h
I just replaced dummy values to store the Ray/BLASInstance mask with 32 bits. I was not sure how to store it in the RayEx since there is no dummy padding so I prefer to let you decide (if you want to add support for that in the double precision bvh).
I think we could also just use 8 bits, as OptiX does, and store those 8 bits in the RayEx instIdx top bits field, since I am sure that 56 bits to store the instance id should be sufficient for any pathtracer 😄 and this will require to modify the BLASInstanceEx and replace the dummy 64 bits with the mask.
Hope this helps!!
> Simple support for ray/instance mask as discussed in #153

- tiny_bvh.h
Geometry that would produce highly degenerate BVHs could stomp memory by writing outside the task stack. This fix stops splitting once the task stack is full.
> Fix task stack overflows

- tiny_bvh.h
Compiling 844a2cd6911ac6bd1eddd50790110acb8e80cdff with NDK 27.2.12479018, I got the following error:
```
tinybvh/tiny_bvh.h:227:80: error: use of undeclared identifier '_aligned_malloc'; did you mean 'aligned_alloc'?
227 | inline void* malloc64( size_t size, void* = nullptr ) { return size == 0 ? 0 : _ALIGNED_ALLOC( 64, size ); }
|                                                                                ^
tinybvh/tiny_bvh.h:222:40: note: expanded from macro '_ALIGNED_ALLOC'
222 | #define _ALIGNED_ALLOC(alignment,size) _aligned_malloc( alignment, size );
|                                        ^
Android/Sdk/ndk/27.2.12479018/toolchains/llvm/prebuilt/windows-x86_64/bin/../sysroot/usr/include/stdlib.h:88:17: note: 'aligned_alloc' declared here
88 | void* _Nullable …
```
> Use 'aligned_alloc' function with API Level 28 and later.

- .gitignore
- README.md
- tiny_bvh.h
- tiny_ocl.h
This is a small set of fixes so that the four example programs compile and run without issue on a MacOS machine with "Apple Silicon" (i.e., their ARM-based CPU).
I updated tiny_ocl.h to use the stock OpenCL framework, to avoid having to install additional libraries when I was building locally. (It comes with the standard toolchain install via Xcode or the Command Line Tools installer.) You might prefer to keep it the way it was, in which case I'm happy to drop that out. (Ditto anything else you'd like changed.)
Mac fixes
- On arm 64 on Mac (Apple Silicon), neon is always available, but __NEON__ isn't defined, so update the warning path for this
- Fix some clashing definitions for SIMDVEC4 etc. on this path
- Fix some v3/v4 compile issues
- Fix e0->v0 typo in BVH_SoA::Intersect
- Update …
> Mac fixes (for vanilla toolchain)

- tiny_bvh.h
__mm_and_epi32 is not defined in sse4.2 and is using vpand AVX instruction on MSVC.
> Switch to _mm_and_si128 to fix compile error on gcc with sse4.2

- tiny_bvh.h
BVH::Build() can create trees up to 256 levels deep so BVH::Intersect() needs at least that much stack to handle all possible trees.
> Fix node stack overflow in BVH::Intersect()

- README.md
- tiny_bvh.h
- tiny_bvh_foliage.cpp
- tiny_bvh_speedtest.cpp
- tiny_scene.h
- tmpl8/tiny_bvh_gltf_demo.vcxproj
- tmpl8/tiny_bvh_gltf_demo.vcxproj.filters
- tmpl8/tiny_bvh_gltf_demo.vcxproj.user
Changelog:
- Eliminated warnings when compiling using -Wall (issue #217)
- Improved use of JobSystem (issue #221)
- Opacity Micromaps now work with general N (issue #218)
- Faster full-sweep builder (issue #222)
- glm can now actually be used for vector types (issue #215)
- BVH4_CPU / BVH8_CPU serialization fix
Thanks to all contributors and issue reporters!
> Merging dev into main.
